baseURL = 'https://TheGregggg.github.io/yesport/'
languageCode = 'en-us'
title = 'Yesport'
theme = 'ananke'
[params]
    commentoEnable = true
    favicon = "favicon.png"
    site_logo = "logo.png"
    recent_posts_number = 10

SectionPagesMenu = "main"
Paginate = 10

[menu]
[[menu.main]]
  name = 'Esport'
  pageRef = '/categories/general'
  weight = 10
[[menu.main]]
  name = 'Smash'
  pageRef = '/categories/smash'
  weight = 20
[[menu.main]]
  name = 'CSGO'
  pageRef = '/categories/csgo'
  weight = 30
[[menu.main]]
  name = 'Trackmania'
  pageRef = '/categories/trackmania'
  weight = 40
[[menu.main]]
  name = 'Splatoon'
  pageRef = '/categories/splatoon'
  weight = 50
[[menu.main]]
  name = 'Everything'
  pageRef = '/categories'
  weight = 60