baseURL = 'https://TheGregggg.github.io/yesport/'
languageCode = 'en-us'
title = 'Yesport'
theme = 'ananke'
[params]
    commentoEnable = true

SectionPagesMenu = "main"
[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Products'
  pageRef = '/products'
  weight = 20
[[menu.main]]
  name = 'Services'
  pageRef = '/services'
  weight = 30